2022-03-19 16:30:37,891  INFO Microsoft.Hosting.Lifetime.? [?] - MESSAGE: Application started. Press Ctrl+C to shut down.
 2022-03-19 16:30:37,906  INFO Microsoft.Hosting.Lifetime.? [?] - MESSAGE: Hosting environment: Development
 2022-03-19 16:30:37,908  INFO Microsoft.Hosting.Lifetime.? [?] - MESSAGE: Content root path: C:\Cognizant\Projects\AuthorizationModule\AuthorizationModule
 2022-03-19 16:59:00,970 ERROR Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.? [?] - MESSAGE: An unhandled exception has occurred while executing the request.
 System.Exception: Can not find user with given credentials
   at AuthorizationModule.Services.AuthService.Login(User user) in C:\Cognizant\Projects\AuthorizationModule\AuthorizationModule\Services\AuthService.cs:line 24
   at AuthorizationModule.Controllers.UserController.Login(User user) in C:\Cognizant\Projects\AuthorizationModule\AuthorizationModule\Controllers\UserController.cs:line 26
   at lambda_method36(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2022-03-19 16:59:01,004 ERROR AuthorizationModule.Extensions.ExceptionMiddlewareExtensions.? [?] - MESSAGE: Can not find user with given credentials : AuthorizationModule.Extensions.ExceptionMiddlewareExtensions+<>c+<<ConfigureExceptionHandler>b__1_1>d
 